const mongoose = require("mongoose");

const PlanSchema = new mongoose.Schema(
  {
    slug: { type: String, required: true, unique: true, trim: true, lowercase: true, index: true },
    name: { type: String, required: true, trim: true, index: true },
    description: { type: String, default: "" },
    pricing: {
      currency: { type: String, default: "INR" },
      originalPricePaise: { type: Number, default: null, min: 0 },
      discountedPricePaise: { type: Number, default: null, min: 0 },
      gstPercent: { type: Number, default: 18, min: 0, max: 100 },
      taxMode: { type: String, enum: ["exclusive", "inclusive", "none"], default: "exclusive" },
      billingCycle: { type: String, enum: ["monthly", "quarterly", "yearly", "lifetime"], default: "monthly" },
    },
    razorpayPlanId: { type: String, default: "", index: true },
    razorpayPlanConfigHash: { type: String, default: "" },
    razorpayPlanSyncedAt: { type: Date, default: null },
    trial: {
      enabled: { type: Boolean, default: false },
      days: { type: Number, default: 0, min: 0, max: 365 },
    },
    computedPreviewSnapshot: {
      discountAmountPaise: { type: Number, default: 0 },
      discountPercent: { type: Number, default: 0 },
      gstAmountPaise: { type: Number, default: 0 },
      payableAmountPaise: { type: Number, default: 0 },
    },
    buttonText: { type: String, default: "" },
    badgeText: { type: String, default: "" },
    badgeType: {
      type: String,
      enum: ["none", "popular", "best_value", "recommended", "limited_offer", "enterprise", "coming_soon"],
      default: "none",
    },
    cardColor: { type: String, enum: ["blue", "green", "purple", "gold", "slate"], default: "blue" },
    icon: { type: String, default: "⭐" },
    status: { type: String, enum: ["draft", "in_review", "published", "archived", "disabled"], default: "in_review", index: true },
    publicVisible: { type: Boolean, default: true, index: true },
    purchasable: { type: Boolean, default: true, index: true },
    recommended: { type: Boolean, default: false },
    sortOrder: { type: Number, default: 1, min: 1, max: 5, index: true },
    features: {
      dashboardPageAccess: { type: Boolean, default: false },
      templatesPageAccess: { type: Boolean, default: false },
      campaignsPageAccess: { type: Boolean, default: false },
      contactsPageAccess: { type: Boolean, default: false },
      inboxPageAccess: { type: Boolean, default: false },
      crmPageAccess: { type: Boolean, default: false },
      flowsPageAccess: { type: Boolean, default: false },
      walletPageAccess: { type: Boolean, default: false },
      linksPageAccess: { type: Boolean, default: false },
      automationPageAccess: { type: Boolean, default: false },
      aiAgentsPageAccess: { type: Boolean, default: false },
      activityPageAccess: { type: Boolean, default: false },
      apiKeysPageAccess: { type: Boolean, default: false },
      apiReportsPageAccess: { type: Boolean, default: false },
      campaignApiAccess: { type: Boolean, default: false },
      externalChatApiAccess: { type: Boolean, default: false },
      crmAccess: { type: Boolean, default: false },
      employeeAccess: { type: Boolean, default: false },
      leadDistributionAccess: { type: Boolean, default: false },
      analyticsAccess: { type: Boolean, default: false },
      exportAccess: { type: Boolean, default: false },
      automationAccess: { type: Boolean, default: false },
      apiKeyAccess: { type: Boolean, default: false },
      whatsAppBroadcastAccess: { type: Boolean, default: false },
      liveChatAccess: { type: Boolean, default: false },
      multiAgentInboxAccess: { type: Boolean, default: false },
      clickToWhatsAppAdsAccess: { type: Boolean, default: false },
      templateMessageApiAccess: { type: Boolean, default: false },
      smartAudienceSegregationAccess: { type: Boolean, default: false },
      broadcastRetargetingAccess: { type: Boolean, default: false },
      smartCampaignManagerAccess: { type: Boolean, default: false },
      campaignSchedulerAccess: { type: Boolean, default: false },
      campaignClickTrackingAccess: { type: Boolean, default: false },
      csvCampaignSchedulerAccess: { type: Boolean, default: false },
      carouselClickTrackingAccess: { type: Boolean, default: false },
      automaticFailedRetryAccess: { type: Boolean, default: false },
      smartAgentRoutingAccess: { type: Boolean, default: false },
      customAgentRulesAccess: { type: Boolean, default: false },
      projectApiAccess: { type: Boolean, default: false },
      webhookAccess: { type: Boolean, default: false },
      webhookApiAccess: { type: Boolean, default: false },
      developerApiAccess: { type: Boolean, default: false },
      templateTtlAccess: { type: Boolean, default: false },
      downloadReportsAccess: { type: Boolean, default: false },
      numberMaskingAccess: { type: Boolean, default: false },
      duplicateCsvContactsAccess: { type: Boolean, default: false },
      multiCtwaChatflowTriggerAccess: { type: Boolean, default: false },
      chatflowDelayAccess: { type: Boolean, default: false },
      chatflowTimeoutAccess: { type: Boolean, default: false },
      prioritySupportAccess: { type: Boolean, default: false },
      turboOnboardingAccess: { type: Boolean, default: false },
      dedicatedAccountManagerAccess: { type: Boolean, default: false },
      userAccessControlAccess: { type: Boolean, default: false },
      whiteLabelAccess: { type: Boolean, default: false },
    },
    limits: {
      maxContacts: { type: Number, default: 0 },
      maxTemplates: { type: Number, default: 0 },
      maxEmployees: { type: Number, default: 0 },
      maxApiKeys: { type: Number, default: 0 },
      maxCampaignsPerMonth: { type: Number, default: 0 },
      maxContactsExport: { type: Number, default: 0 },
      // Backward compatibility for older plans. New plans should use `maxContactsExport`.
      maxExportsPerMonth: { type: Number, default: 0 },
      maxStorageMb: { type: Number, default: 0 },
      maxAgents: { type: Number, default: 0 },
      maxTags: { type: Number, default: 0 },
      maxCustomAttributes: { type: Number, default: 0 },
      maxWebhooks: { type: Number, default: 0 },
      messageRatePerSec: { type: Number, default: 0 },
      maxFlows: { type: Number, default: 0 },
      maxTeams: { type: Number, default: 0 },
      maxProjects: { type: Number, default: 0 },
      maxMediaSizeMb: { type: Number, default: 0 },
      dailyMessageLimit: { type: Number, default: 0 },
    },
    entitlements: { type: mongoose.Schema.Types.Mixed, default: {} },
    featureRows: [
      {
        label: { type: String, required: true, trim: true },
        type: { type: String, enum: ["functionality", "limit", "text"], required: true },
        functionalityKey: { type: String, default: "" },
        limitKey: { type: String, default: "" },
        value: { type: mongoose.Schema.Types.Mixed, default: null },
        included: { type: Boolean, default: true },
        sortOrder: { type: Number, default: 0 },
      },
    ],
    displayFeatures: [{ type: String, trim: true }],
    unavailableFeatures: [{ type: String, trim: true }],
    addonServices: [{ type: String, trim: true }],
    review: {
      submittedAt: { type: Date, default: null },
      publishedAt: { type: Date, default: null },
      reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
      reviewNote: { type: String, default: "" },
    },
    version: { type: Number, default: 1, min: 1 },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    deletedAt: { type: Date, default: null, index: true },
    deletedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  },
  { timestamps: true }
);

PlanSchema.pre("save", function () {
  if (!this.isNew && this.isModified()) {
    this.version = Number(this.version || 1) + 1;
  }
});

const Plan = mongoose.model("Plan", PlanSchema);

module.exports = { Plan };
