const WORKSPACE_PERMISSIONS = [
  "workspace.view",
  "workspace.update",
  "members.view",
  "members.invite",
  "members.manage",
  "billing.view",
  "billing.manage",
  "plan.manage",
  "whatsapp.view",
  "whatsapp.connect",
  "whatsapp.disconnect",
  "templates.view",
  "templates.create",
  "templates.delete",
  "inbox.view",
  "inbox.reply",
  "contacts.view",
  "contacts.create",
  "contacts.update",
  "contacts.delete",
  "campaigns.view",
  "campaigns.create",
  "campaigns.send",
  "analytics.view",
  "settings.view",
  "settings.update",
];

const ROLE_PERMISSIONS = {
  owner: WORKSPACE_PERMISSIONS,
  admin: WORKSPACE_PERMISSIONS.filter((key) => key !== "plan.manage"),
  manager: [
    "workspace.view",
    "members.view",
    "whatsapp.view",
    "templates.view",
    "templates.create",
    "templates.delete",
    "inbox.view",
    "inbox.reply",
    "contacts.view",
    "contacts.create",
    "contacts.update",
    "contacts.delete",
    "campaigns.view",
    "campaigns.create",
    "campaigns.send",
    "analytics.view",
    "settings.view",
  ],
  agent: ["workspace.view", "templates.view", "inbox.view", "inbox.reply", "contacts.view", "contacts.create", "contacts.update"],
  viewer: ["workspace.view", "templates.view", "inbox.view", "contacts.view", "campaigns.view", "analytics.view"],
};

module.exports = { ROLE_PERMISSIONS, WORKSPACE_PERMISSIONS };
