const { COMMERCE_PERMISSIONS, COMMERCE_READ_PERMISSIONS, COMMERCE_MANAGER_PERMISSIONS, COMMERCE_AGENT_PERMISSIONS } = require("@modules/commerce/constants/permissions");

const WORKSPACE_PERMISSIONS = [
  "commerce.delivery.view", "commerce.delivery.manage", "commerce.delivery.override",
  ...COMMERCE_PERMISSIONS,
  "workspace.view",
  "workspace.update",
  "members.view",
  "members.invite",
  "members.manage",
  "billing.view",
  "billing.manage",
  "aiBilling.view",
  "aiBilling.manage",
  "aiBilling.budget",
  "aiBilling.reports",
  "plan.manage",
  "whatsapp.view",
  "whatsapp.connect",
  "whatsapp.disconnect",
  "templates.view",
  "templates.create",
  "templates.delete",
  "inbox.view",
  "inbox.reply",
  "contacts.view",
  "contacts.create",
  "contacts.update",
  "contacts.delete",
  "campaigns.view",
  "campaigns.create",
  "campaigns.send",
  "automation.view",
  "automation.create",
  "automation.update",
  "automation.manage",
  "analytics.view",
  "ecommerce.view",
  "ecommerce.manage",
  "settings.view",
  "settings.update",
];

const ROLE_PERMISSIONS = {
  owner: WORKSPACE_PERMISSIONS,
  admin: WORKSPACE_PERMISSIONS.filter((key) => key !== "plan.manage"),
  manager: [
    "commerce.delivery.view", "commerce.delivery.manage",
    ...COMMERCE_MANAGER_PERMISSIONS,
    "workspace.view",
    "members.view",
    "whatsapp.view",
    "templates.view",
    "templates.create",
    "templates.delete",
    "inbox.view",
    "inbox.reply",
    "contacts.view",
    "contacts.create",
    "contacts.update",
    "contacts.delete",
    "campaigns.view",
    "campaigns.create",
    "campaigns.send",
    "automation.view",
    "automation.create",
    "automation.update",
    "automation.manage",
    "analytics.view",
    "ecommerce.view",
    "ecommerce.manage",
    "settings.view",
    "aiBilling.view",
    "aiBilling.budget",
    "aiBilling.reports",
  ],
  agent: [...COMMERCE_AGENT_PERMISSIONS, "workspace.view", "templates.view", "inbox.view", "inbox.reply", "contacts.view", "contacts.create", "contacts.update"],
  viewer: [...COMMERCE_READ_PERMISSIONS, "workspace.view", "templates.view", "inbox.view", "contacts.view", "campaigns.view", "automation.view", "analytics.view", "ecommerce.view"],
};

module.exports = { ROLE_PERMISSIONS, WORKSPACE_PERMISSIONS };
