const express = require("express");
const { auth } = require("@core/middleware/auth");
const { requireWorkspace } = require("@core/middleware/requireWorkspace");
const { requireWorkspacePermission: permission } = require("@modules/workspaces/middleware/requireWorkspacePermission");
const { HttpError } = require("@shared/utils/httpError");
const limits = require("@core/middleware/rateLimiters");
const readiness = require("../services/paymentsReadiness.service");
const controller = require("../controllers/payments.controller");
const router = express.Router();
const safe = (handler) => (req, res, next) => Promise.resolve().then(() => handler(req, res, next)).catch((error) =>
  next(error instanceof HttpError ? error : new HttpError(503, "Commerce payment operation failed. Check status before retrying.")));
const ready = safe(async (_req, _res, next) => { await readiness.assertPaymentsReady(); next(); });
const json = (req, _res, next) => req.is("application/json") ? next() : next(new HttpError(415, "Commerce payments require application/json."));
router.use((_req, res, next) => { res.set({ "Cache-Control": "no-store", "Referrer-Policy": "no-referrer" }); next(); });
router.post("/webhooks/razorpay/:gatewayId", limits.ecommerceWebhook, json, ready, safe(controller.receive));
const view = [auth, requireWorkspace, permission("commerce.payments.view"), ready, limits.ecommerceRead];
const manage = [auth, requireWorkspace, permission("commerce.payments.manage"), ready, limits.ecommerceConnect, json];
router.get("/payments/settings", ...view, safe(controller.settings));
router.patch("/payments/settings", ...manage, safe(controller.changeSettings));
router.post("/payments/gateways/:gatewayId/webhook", auth, requireWorkspace, permission("commerce.gateway.manage"), ready, limits.ecommerceConnect, json, safe(controller.configure));
router.post("/payments/gateways/:gatewayId/verify-identity", auth, requireWorkspace, permission("commerce.gateway.manage"), ready, limits.ecommerceConnect, json, safe(controller.verifyIdentity));
router.get("/payments/events", ...view, safe(controller.read("listEvents")));
router.post("/payments/events/:eventId/retry", ...manage, safe(controller.change("retryEvent")));
router.get("/payments/attempts/:attemptId", ...view, safe(controller.attempt));
router.post("/payments/attempts/:attemptId/cancel", ...manage, safe(controller.change("cancel")));
router.get("/payments", ...view, safe(controller.read("list")));
router.get("/payments/:paymentId/refunds", ...view, safe(controller.orderRead("refunds")));
router.post("/orders/:orderId/payment-requests", ...manage, permission("commerce.orders.manage"), safe(controller.checkout));
router.get("/orders/:orderId/payment-requests", ...view, safe(controller.orderRead("attempts")));
router.post("/orders/:orderId/reconcile", ...manage, safe(controller.change("reconcileOrder")));
router.get("/orders/:orderId/notifications", ...view, safe(controller.orderRead("notifications")));
module.exports = router;
