require("module-alias/register");
const { test } = require("node:test"), assert = require("node:assert/strict"), express = require("express"), jwt = require("jsonwebtoken"), { once } = require("node:events");
const { jwtSecret } = require("@core/config/env"), { User } = require("@infra/database/User"), { Workspace } = require("@infra/database/Workspace"), { WorkspaceMember } = require("@infra/database/WorkspaceMember");
const readiness = require("../delivery/readiness"), repo = require("../delivery/repository");
test("delivery HTTP routes preserve legacy paths and enforce merchant permissions and rider isolation", async (t) => {
  const ws = "100000000000000000000001", user = "200000000000000000000001"; let role = "viewer", member = true, rider = null, notices = [];
  t.mock.method(readiness, "ready", async () => {});
  t.mock.method(User, "findById", () => ({ select: async () => ({ _id: user, role: "user", status: "active", tokenVersion: 0 }) }));
  t.mock.method(Workspace, "findOne", async ({ _id }) => _id === ws ? { _id: ws, ownerId: "someone-else" } : null);
  t.mock.method(WorkspaceMember, "findOne", async () => member ? { role, permissionsOverride: {} } : null);
  t.mock.method(repo, "list", async (kind, scope, options) => { assert.equal(scope, ws); assert.ok(options.limit <= 50); return kind === "Notice" ? notices : []; });
  t.mock.method(repo, "byUser", async () => rider);
  const app = express(); app.use(express.json()); app.use("/commerce", require("../delivery/routes")); app.get("/commerce/legacy", (_req, res) => res.json({ legacy: true }));
  app.use(require("@core/middleware/errorHandler").errorHandler);
  const server = app.listen(0, "127.0.0.1"); await once(server, "listening"); t.after(async () => { server.closeAllConnections(); await new Promise((r) => server.close(r)); });
  const base = `http://127.0.0.1:${server.address().port}/commerce`, headers = { Authorization: `Bearer ${jwt.sign({ sub: user, tokenVersion: 0 }, jwtSecret, { expiresIn: "1m" })}`, "x-workspace-id": ws, "Content-Type": "application/json" };
  assert.equal((await fetch(`${base}/legacy`)).status, 200); assert.equal((await fetch(`${base}/outlets`)).status, 401);
  assert.equal((await fetch(`${base}/outlets`, { headers })).status, 403);
  const recommendationPath = `${base}/deliveries/300000000000000000000001/recommendations`;
  assert.equal((await fetch(recommendationPath, { method: "POST", headers, body: JSON.stringify({ revision: 1, mode: "suggested" }) })).status, 403);
  assert.equal((await fetch(`${base}/delivery-settings`, { method: "PUT", headers, body: "{}" })).status, 403);
  assert.equal((await fetch(`${base}/delivery-trips/assign`, { method: "POST", headers, body: "{}" })).status, 403);
  assert.equal((await fetch(`${base}/delivery-zones`, { method: "POST", headers, body: "{}" })).status, 403);
  assert.equal((await fetch(`${base}/couriers/300000000000000000000001/batching`, { method: "PATCH", headers, body: "{}" })).status, 403);
  assert.equal((await fetch(`${base}/deliveries/300000000000000000000001/action`, { method: "POST", headers, body: JSON.stringify({ revision: 1, action: "pause_auto" }) })).status, 403);
  role = "manager"; assert.equal((await fetch(`${base}/outlets`, { headers })).status, 200);
  t.mock.method(require("../delivery/routing"), "recommend", async (scope, deliveryId, input) => { assert.equal(scope, ws); assert.equal(deliveryId, "300000000000000000000001"); assert.equal(input.mode, "suggested"); return { candidates: [], confirmationRequired: true }; });
  assert.equal((await fetch(recommendationPath, { method: "POST", headers, body: JSON.stringify({ revision: 1, mode: "suggested" }) })).status, 200);
  assert.equal((await fetch(recommendationPath, { method: "POST", headers, body: JSON.stringify({ revision: 1, mode: "suggested", workspaceId: "foreign" }) })).status, 400);
  assert.equal((await fetch(`${base}/outlets?limit=1000`, { headers })).status, 400);
  assert.equal((await fetch(`${base}/outlets`, { method: "POST", headers, body: JSON.stringify({ workspaceId: ws }) })).status, 400);
  assert.equal((await fetch(`${base}/rider/me`, { headers })).status, 403);
  notices = [{ _id: "400000000000000000000001", kind: "awaiting_manual_assignment", orderId: "300000000000000000000001", reason: "Assign manually", createdAt: new Date() }];
  const firstNotices = await (await fetch(`${base}/delivery-notifications`, { headers })).json();
  const recoveredNotices = await (await fetch(`${base}/delivery-notifications`, { headers })).json();
  assert.equal(firstNotices.items.length, 1); assert.deepEqual(recoveredNotices, firstNotices);
  member = false; assert.equal((await fetch(`${base}/outlets`, { headers })).status, 404);
  // Rider scope is bound to its authenticated profile, never the workspace header.
  rider = { _id: "300000000000000000000001", workspaceId: ws, userId: user, active: true, currentDeliveryId: null };
  t.mock.method(require("../repositories/orders.repository"), "workspaceActive", async (scope) => String(scope) === ws);
  assert.equal((await fetch(`${base}/rider/me`, { headers: { ...headers, "x-workspace-id": "foreign" } })).status, 200);
  let saved; t.mock.method(require("../delivery/service"), "save", async (_kind, _record, patch) => { saved = patch; return {}; });
  t.mock.method(require("../delivery/routingSettings"), "get", async () => ({ locationMaxAgeSeconds: 120 }));
  assert.equal((await fetch(`${base}/rider/location`, { method: "POST", headers, body: JSON.stringify({ latitude: 26, longitude: 80, accuracy: 10, capturedAt: new Date(Date.now() - 90000).toISOString() }) })).status, 200);
  assert.deepEqual(saved.geoPoint, { type: "Point", coordinates: [80, 26] }); assert.equal(saved.location.source, "gps");
  assert.equal((await fetch(recommendationPath, { method: "POST", headers, body: JSON.stringify({ revision: 1, mode: "suggested" }) })).status, 404);
  rider.active = false; assert.equal((await fetch(`${base}/rider/me`, { headers })).status, 403);
});
