require("module-alias/register");
const { test } = require("node:test"), assert = require("node:assert/strict"), express = require("express"), jwt = require("jsonwebtoken"), { once } = require("node:events");
const { jwtSecret } = require("@core/config/env");
const { User } = require("@infra/database/User"), { Workspace } = require("@infra/database/Workspace"), { WorkspaceMember } = require("@infra/database/WorkspaceMember");
const { errorHandler } = require("@core/middleware/errorHandler"), { paymentErrorBoundary } = require("../routes/paymentsHttp");
const readiness = require("../services/paymentsReadiness.service"), catalogReady = require("../services/catalogReadiness.service");
const operations = require("../services/operations.service"), messages = require("../services/commerceMessages.service"), repo = require("../repositories/operations.repository");
const audit = require("@shared/services/auditLog.service"), credentials = require("@shared/services/credentialsService");
test("Stage 6 HTTP endpoints enforce actual membership, role overrides, validation and private responses", async (t) => {
  const ws = "100000000000000000000001", uid = "200000000000000000000001", id = "400000000000000000000001";
  let role = "viewer", member = true, override = {}, sends = 0;
  t.mock.method(User, "findById", () => ({ select: async () => ({ _id: uid, role: "user", status: "active", tokenVersion: 0 }) }));
  t.mock.method(Workspace, "findOne", async (q) => q._id === ws ? { _id: ws, ownerId: "other", isActive: true, status: "active" } : null);
  t.mock.method(WorkspaceMember, "findOne", async () => member ? { role, permissionsOverride: override } : null);
  t.mock.method(readiness, "assertPaymentsReady", async () => {}); t.mock.method(catalogReady, "assertCatalogReady", async () => {});
  t.mock.method(audit, "writeAuditLog", async () => {});
  t.mock.method(credentials, "getCredentialsForUser", async () => ({ wabaId: "123", phoneNumberId: "456" }));
  t.mock.method(repo, "inboxOrders", async (workspace, q) => { assert.equal(workspace, ws); assert.equal(q.to, "919999999999"); return []; });
  t.mock.method(operations, "fulfill", async (workspace, orderId) => { assert.equal(workspace, ws); assert.equal(orderId, id); return { id, status: "processing" }; });
  t.mock.method(operations, "retryNotification", async () => ({ id, status: "pending" }));
  t.mock.method(messages, "send", async (workspace, user) => { assert.equal(workspace, ws); assert.equal(user, uid); sends++; return { id, status: "sent" }; });
  // Re-load route closures so this test cannot accidentally use imports from another test.
  delete require.cache[require.resolve("../routes/operations.routes")];
  const app = express(); app.use(express.json()); const router = require("../routes/operations.routes");
  app.use("/commerce", router); app.use("/api/commerce", router); app.use(paymentErrorBoundary); app.use(errorHandler);
  const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
  t.after(async () => { server.closeAllConnections(); await new Promise((resolve) => server.close(resolve)); delete require.cache[require.resolve("../routes/operations.routes")]; });
  const base = `http://127.0.0.1:${server.address().port}/api/commerce`, token = jwt.sign({ sub: uid, tokenVersion: 0 }, jwtSecret, { expiresIn: "1m" });
  const headers = { Authorization: `Bearer ${token}`, "x-workspace-id": ws, "Content-Type": "application/json" };
  const post = (path, data, h = headers) => fetch(`${base}${path}`, { method: "POST", headers: h, body: JSON.stringify(data) });
  assert.equal((await fetch(`${base}/access`)).status, 401);
  const access = await fetch(`${base}/access`, { headers }); assert.equal(access.status, 200); assert.equal(access.headers.get("cache-control"), "no-store"); assert.equal((await access.json()).capabilities.native, false);
  member = false; assert.equal((await fetch(`${base}/access`, { headers })).status, 404); member = true;
  assert.equal((await post(`/orders/${id}/fulfillment`, { revision: 1, status: "processing" })).status, 403);
  const message = { kind: "catalog", to: "919999999999", idempotencyKey: "message_intent_test_01" };
  assert.equal((await post("/messages", message)).status, 403);
  role = "agent"; assert.equal((await post("/messages", message)).status, 202);
  override = { "inbox.reply": false }; assert.equal((await post("/messages", message)).status, 403); override = {};
  assert.equal((await post("/messages", { ...message, amount: 1 })).status, 400);
  assert.equal((await post("/messages", message, { ...headers, "Content-Type": "text/plain" })).status, 415);
  assert.equal((await post(`/notifications/${id}/retry`, {})).status, 202);
  role = "manager"; assert.equal((await post(`/orders/${id}/fulfillment`, { revision: 1, status: "processing" })).status, 200);
  assert.equal((await post(`/orders/${id}/fulfillment`, { revision: 1, status: "paid" })).status, 400);
  assert.equal((await fetch(`${base}/orders/inbox?environment=test&to=919999999999`, { headers })).status, 200);
  assert.equal((await fetch(`${base}/orders/inbox?to=919999999999`, { headers })).status, 400);
  const malformed = await fetch(`${base}/messages`, { method: "POST", headers, body: '{"secret":"do-not-echo",invalid' });
  assert.equal(malformed.status, 400); assert.equal((await malformed.text()).includes("do-not-echo"), false); assert.equal(sends, 1);
});
