require("module-alias/register");
const { test } = require("node:test");
const assert = require("node:assert/strict");
const express = require("express");
const jwt = require("jsonwebtoken");
const { once } = require("node:events");
const { jwtSecret } = require("@core/config/env");
const { User } = require("@infra/database/User");
const { Workspace } = require("@infra/database/Workspace");
const { WorkspaceMember } = require("@infra/database/WorkspaceMember");
const { errorHandler } = require("@core/middleware/errorHandler");
const { orderErrorBoundary } = require("../routes/ordersHttp");
const readiness = require("../services/ordersReadiness.service");
const service = require("../services/orders.service");
const audit = require("@shared/services/auditLog.service");
const { HttpError } = require("@shared/utils/httpError");
test("order HTTP APIs enforce permissions and scoped query validation while fulfillment uses only its bearer capability", async (t) => {
  const ws = "100000000000000000000001", user = "200000000000000000000001", id = "300000000000000000000001", token = "a".repeat(64);
  let role = "viewer", member = true, enabled = true, calls = 0, authCalls = 0;
  t.mock.method(User, "findById", () => { authCalls++; return { select: async () => ({ _id: user, role: "user", status: "active", tokenVersion: 0 }) }; });
  t.mock.method(Workspace, "findOne", async (query) => query._id === ws ? { _id: ws, ownerId: "other", isActive: true, status: "active" } : null);
  t.mock.method(WorkspaceMember, "findOne", async () => member ? { role, permissionsOverride: {} } : null);
  t.mock.method(readiness, "assertOrdersReady", async () => { if (!enabled) throw new HttpError(503, "Disabled"); });
  t.mock.method(audit, "writeAuditLog", async (_req, data) => { assert.equal(JSON.stringify(data).includes("address"), false); });
  t.mock.method(service, "list", async (workspace, query) => {
    calls++; assert.equal(workspace, ws); assert.equal(query.environment, "live"); assert.equal(query.limit, 2);
    return { items: [], nextCursor: null };
  });
  t.mock.method(service, "edit", async (workspace, orderId, input) => {
    calls++; assert.equal(workspace, ws); assert.equal(orderId, id); assert.equal(input.revision, 1); return { id, revision: 2 };
  });
  t.mock.method(service, "get", async () => { throw new Error("private address database error"); });
  t.mock.method(service, "getFulfillment", async (supplied) => { assert.equal(supplied, token); return { orderNumber: "AWC-test" }; });
  t.mock.method(service, "submitFulfillment", async (supplied, input) => {
    assert.equal(supplied, token); assert.equal(input.fulfillmentMethod, "pickup"); return { status: "needs_review" };
  });
  const app = express(); app.use(express.json());
  app.use("/api/commerce", require("../routes/orders.routes"));
  app.get("/api/commerce/catalog", (_req, res) => res.json({ catalog: "unaffected" }));
  app.use(orderErrorBoundary); app.use(errorHandler);
  const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
  t.after(async () => { server.closeAllConnections(); await new Promise((resolve) => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}/api/commerce`;
  const accessToken = jwt.sign({ sub: user, tokenVersion: 0 }, jwtSecret, { expiresIn: "1m" });
  const headers = { Authorization: `Bearer ${accessToken}`, "x-workspace-id": ws, "Content-Type": "application/json" };
  assert.equal((await fetch(`${base}/orders?environment=live&limit=2`)).status, 401);
  assert.equal((await fetch(`${base}/orders?environment=live&limit=2`, { headers })).status, 200);
  assert.equal((await fetch(`${base}/orders?limit=2`, { headers })).status, 400);
  assert.equal((await fetch(`${base}/orders?environment=live&limit=1000`, { headers })).status, 400);
  const input = { revision: 1, fulfillmentMethod: "pickup", deliveryPrice: "0", deliveryTaxRateBps: null };
  const edit = (body = input, supplied = headers) => fetch(`${base}/orders/${id}`, { method: "PATCH", headers: supplied, body: JSON.stringify(body) });
  assert.equal((await edit()).status, 403); role = "manager";
  assert.equal((await edit({ ...input, paymentStatus: "captured" })).status, 400);
  assert.equal((await edit()).status, 200); assert.equal(calls, 2);
  member = false; assert.equal((await edit()).status, 404); member = true;
  enabled = false; assert.equal((await edit()).status, 503); enabled = true;
  assert.equal((await edit(input, { ...headers, "Content-Type": "text/plain" })).status, 415);
  const failure = await fetch(`${base}/orders/${id}`, { headers }); assert.equal(failure.status, 503); assert.equal((await failure.text()).includes("private"), false);
  const malformed = await fetch(`${base}/orders/${id}`, { method: "PATCH", headers, body: '{"address":"private-address",bad' });
  assert.equal(malformed.status, 400); assert.equal((await malformed.text()).includes("private-address"), false);
  const before = authCalls;
  assert.equal((await fetch(`${base}/catalog`, { headers })).status, 200); assert.equal(authCalls, before);
  assert.equal((await fetch(`${base}/fulfillment`)).status, 401);
  const publicHeaders = { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "x-workspace-id": "untrusted" };
  const publicView = await fetch(`${base}/fulfillment`, { headers: publicHeaders }); assert.equal(publicView.status, 200);
  assert.equal(publicView.headers.get("cache-control"), "no-store"); assert.equal(authCalls, before);
  assert.equal((await fetch(`${base}/fulfillment`, { method: "POST", headers: publicHeaders, body: JSON.stringify({ fulfillmentMethod: "pickup", workspaceId: ws }) })).status, 400);
  assert.equal((await fetch(`${base}/fulfillment`, { method: "POST", headers: publicHeaders, body: JSON.stringify({ fulfillmentMethod: "pickup" }) })).status, 200);
});
