require("module-alias/register");
const { test } = require("node:test");
const assert = require("node:assert/strict");
const express = require("express");
const jwt = require("jsonwebtoken");
const { once } = require("node:events");
const { jwtSecret } = require("@core/config/env");
const { User } = require("@infra/database/User");
const { Workspace } = require("@infra/database/Workspace");
const { WorkspaceMember } = require("@infra/database/WorkspaceMember");
const { errorHandler } = require("@core/middleware/errorHandler");
const { HttpError } = require("@shared/utils/httpError");
const readiness = require("../services/paymentsReadiness.service");
const service = require("../services/payments.service");
const webhooks = require("../services/paymentWebhooks.service");
const audit = require("@shared/services/auditLog.service");
const { registerPaymentRawBody, isPaymentWebhook, paymentErrorBoundary } = require("../routes/paymentsHttp");
test("payment HTTP routes enforce membership, payment permissions, private responses and exact raw bytes on both aliases", async (t) => {
  const ws = "100000000000000000000001", userId = "200000000000000000000001", id = "300000000000000000000001";
  let role = "viewer", member = true, enabled = true, creates = 0, received = 0;
  t.mock.method(User, "findById", () => ({ select: async () => ({ _id: userId, role: "user", status: "active", tokenVersion: 0 }) }));
  t.mock.method(Workspace, "findOne", async (q) => q._id === ws ? { _id: ws, ownerId: "other", isActive: true, status: "active" } : null);
  t.mock.method(WorkspaceMember, "findOne", async () => member ? { role, permissionsOverride: {} } : null);
  t.mock.method(readiness, "assertPaymentsReady", async () => { if (!enabled) throw new HttpError(503, "Disabled"); });
  t.mock.method(audit, "writeAuditLog", async (_req, data) => { assert.equal(JSON.stringify(data).includes("secret"), false); });
  t.mock.method(service, "list", async (workspace) => { assert.equal(workspace, ws); return { items: [] }; });
  t.mock.method(service, "checkout", async (workspace, orderId, user, input) => {
    assert.equal(workspace, ws); assert.equal(orderId, id); assert.equal(user, userId); assert.equal(input.revision, 1); creates++;
    return { id, status: "payable", paymentUrl: "https://rzp.io/i/test" };
  });
  t.mock.method(service, "getAttempt", async () => { throw new Error("secret-request-body"); });
  t.mock.method(webhooks, "receive", async (gateway, raw, signature, eventId) => {
    assert.equal(gateway, id); assert.ok(Buffer.isBuffer(raw)); assert.equal(raw.toString(), '{ "entity": "event" }');
    assert.equal(eventId, "event_test"); if (signature !== "valid") throw new HttpError(401, "Invalid signature"); received++; return { accepted: true };
  });
  const app = express(); registerPaymentRawBody(app);
  const parser = express.json(); app.use((req, res, next) => isPaymentWebhook(req.originalUrl) ? next() : parser(req, res, next));
  app.use("/commerce", require("../routes/payments.routes")); app.use("/api/commerce", require("../routes/payments.routes"));
  app.use(paymentErrorBoundary); app.use(errorHandler);
  const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
  t.after(async () => { server.closeAllConnections(); await new Promise((resolve) => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const token = jwt.sign({ sub: userId, tokenVersion: 0 }, jwtSecret, { expiresIn: "1m" });
  const headers = { Authorization: `Bearer ${token}`, "x-workspace-id": ws, "Content-Type": "application/json" };
  const input = { gatewayConnectionId: id, revision: 1, idempotencyKey: "checkout_example_01" };
  const post = (path, body, supplied = headers) => fetch(`${base}/api/commerce${path}`, { method: "POST", headers: supplied, body: JSON.stringify(body) });
  assert.equal((await fetch(`${base}/api/commerce/payments`)).status, 401);
  assert.equal((await fetch(`${base}/api/commerce/payments?environment=test`, { headers })).status, 200);
  assert.equal((await post(`/orders/${id}/payment-requests`, input)).status, 403);
  role = "manager"; assert.equal((await post(`/orders/${id}/payment-requests`, input)).status, 403);
  role = "admin"; member = false; assert.equal((await post(`/orders/${id}/payment-requests`, input)).status, 404);
  member = true; assert.equal((await post(`/orders/${id}/payment-requests`, { ...input, amountPaise: 1 })).status, 400);
  assert.equal((await post(`/orders/${id}/payment-requests`, input, { ...headers, "Content-Type": "text/plain" })).status, 415);
  const checkout = await post(`/orders/${id}/payment-requests`, input); assert.equal(checkout.status, 202);
  assert.equal(checkout.headers.get("cache-control"), "no-store"); assert.equal(creates, 1);
  enabled = false; assert.equal((await post(`/orders/${id}/payment-requests`, input)).status, 503); enabled = true;
  const failed = await fetch(`${base}/api/commerce/payments/attempts/${id}`, { headers }); assert.equal(failed.status, 503); assert.equal((await failed.text()).includes("secret"), false);
  const invalid = await fetch(`${base}/api/commerce/payments/settings`, { method: "PATCH", headers, body: '{"secret":"do-not-echo",broken' });
  assert.equal(invalid.status, 400); assert.equal((await invalid.text()).includes("do-not-echo"), false);
  for (const prefix of ["/commerce", "/api/commerce", "/API/COMMERCE"]) {
    const url = `${base}${prefix}/webhooks/razorpay/${id}`;
    const webhookHeaders = { "Content-Type": "application/json", "x-razorpay-signature": "valid", "x-razorpay-event-id": "event_test" };
    assert.equal((await fetch(url, { method: "POST", headers: webhookHeaders, body: '{ "entity": "event" }' })).status, 200);
    assert.equal((await fetch(url, { method: "POST", headers: { ...webhookHeaders, "x-razorpay-signature": "wrong" }, body: '{ "entity": "event" }' })).status, 401);
  }
  assert.equal(received, 3);
  const compressed = await fetch(`${base}/api/commerce/webhooks/razorpay/${id}`, { method: "POST", headers: { "Content-Type": "application/json", "Content-Encoding": "gzip" }, body: "not-gzip" });
  assert.equal(compressed.status, 415);
});
