const FEATURE_FUNCTIONALITY_KEYS = Object.freeze([
  "dashboardPageAccess",
  "templatesPageAccess",
  "campaignsPageAccess",
  "contactsPageAccess",
  "inboxPageAccess",
  "crmPageAccess",
  "flowsPageAccess",
  "walletPageAccess",
  "linksPageAccess",
  "automationPageAccess",
  "aiAgentsPageAccess",
  "activityPageAccess",
  "apiKeysPageAccess",
  "apiReportsPageAccess",
  "campaignApiAccess",
  "externalChatApiAccess",
  "employeeAccess",
  "leadDistributionAccess",
  "exportAccess",
  "multiAgentInboxAccess",
  "campaignSchedulerAccess",
  "csvCampaignSchedulerAccess",
  "smartAgentRoutingAccess",
]);

const LIMIT_KEYS = Object.freeze([
  "maxContacts",
  "maxTemplates",
  "maxEmployees",
  "maxApiKeys",
  "maxCampaignsPerMonth",
  "maxContactsExport",
  "maxStorageMb",
  "maxAgents",
  "maxTags",
  "maxCustomAttributes",
  "maxWebhooks",
  "messageRatePerSec",
  "maxFlows",
  "maxMediaSizeMb",
  "dailyMessageLimit",
]);

module.exports = { FEATURE_FUNCTIONALITY_KEYS, LIMIT_KEYS };
